### PR TITLE
Adding Allison Horst's Artwork (finally!)

### PR DESCRIPTION
**Pull request by deblnia**
I've added Allison Horst's artwork in the places it seemed most strictly relevant (mostly dplyr functions and the new tidymodels material). I've also added citations as alt text (can definitely change to be explicit if you prefer). There are also a few unused but course-adjacent images in the folder (the images about patchwork, lubridate, and broom specifically) that I'm still trying to find the best place for (just creating the PR now to make sure this builds). 
Happy to make any changes as always 😄  
Working on #192.

### CODE REVIEW

**Review by bensoltoff — COMMENTED** [review]
A few notes.

1. The syntax is `/img/allison/...` for the filepath. When Hugo renders the site, the static folder moves to the top-level so you can refer to them directly. I'm pushing a commit to update this.
2. Anything in RMarkdown with the `@name` syntax is treated as a pandoc citation. It doesn't cause any errors, but it will pop up a message when you knit the document. Just an explanation of why that occurs.
3. Remember to knit the `.Rmarkdown` file, otherwise the changes are not reflected in the `.markdown` version used to render the site.
4. Unfortunately the alt text for the images only shows if the image does not render. Might be more fair/appropriate to credit Allison Horst at the end of each relevant page (see similar citations I've made for content drawn from/inspired by other resources).

**Comment by bensoltoff** [comment]
I think the only adjustment that needs to be made is the source credit at the bottom of each page. Otherwise it all looks good. Thanks so much for working on this!

**Comment by deblnia** [comment]
Added acknowledgements properly I think! I'm having a bit of trouble knitting all the docs though (it's just a bit of dependency hell for some reason), is there any way the deploy can take care of that? (Happy to work through it if no!)

**Comment by bensoltoff** [comment]
@deblnia Rmd and RMarkdown files could be automatically knitted if I switched to deploying using [Travis CI + GitHub](https://bookdown.org/yihui/blogdown/travis-github.html). However I am not proficient using Travis, the `blogdown` authors discourage this approach, and I like the ability to preview locally before I push to GitHub (for minor updates I don't bother creating a separate branch which means these pushes would immediately go live on the website).

**Review by bensoltoff — APPROVED** [review]
Looks good to go now

**Pull request merged**
